[package]
name = "hackaton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = "2.31.2"
prettytable-rs = "0.6.7"
#rust-ini = "0.11.0"
#sys-info = "0.5.6"
#rust-embed = "1.1.1"
#log = "0.4.1"
